const fs = require('node:fs');
const path = require('node:path');

const repositoryRoot = path.resolve(__dirname, '..');
const readmePath = path.join(repositoryRoot, 'README.md');
const docsSourcePath = path.join(repositoryRoot, 'docs', 'docs-source.json');

function loadJson(filePath) {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function updateSection(documentText, sectionName, renderedSection) {
    const startMarker = `<!-- GENERATED:${sectionName}:START -->`;
    const endMarker = `<!-- GENERATED:${sectionName}:END -->`;

    const startIndex = documentText.indexOf(startMarker);
    const endIndex = documentText.indexOf(endMarker);

    if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
        throw new Error(`Missing generated section markers for "${sectionName}" in README.md`);
    }

    const replacement = `${startMarker}\n${renderedSection}\n${endMarker}`;
    return `${documentText.slice(0, startIndex)}${replacement}${documentText.slice(endIndex + endMarker.length)}`;
}

function renderCommandTable(commands) {
    const lines = [
        '| Command | Purpose |',
        '| --- | --- |',
        ...commands.map((command) => `| \`${command.display}\` | ${command.description} |`)
    ];
    return lines.join('\n');
}

function renderSupportedFileTypes(extensions) {
    const lines = [
        '| Extension | Status |',
        '| --- | --- |',
        ...extensions.map((extension) => `| \`${extension}\` | Ingested by the active Node pipeline |`)
    ];
    return lines.join('\n');
}

function renderRepoLayout(entries) {
    return entries
        .map((entry) => `- \`${entry.path}\` — ${entry.description}`)
        .join('\n');
}

function buildReadme(readmeText, docsSource) {
    let next = readmeText;
    next = updateSection(next, 'commands', renderCommandTable(docsSource.commands));
    next = updateSection(next, 'supported-file-types', renderSupportedFileTypes(docsSource.supportedFileTypes));
    next = updateSection(next, 'repo-layout', renderRepoLayout(docsSource.repoLayout));
    return next;
}

function main() {
    const checkMode = process.argv.includes('--check');
    const docsSource = loadJson(docsSourcePath);
    const currentReadme = fs.readFileSync(readmePath, 'utf8');
    const nextReadme = buildReadme(currentReadme, docsSource);

    if (checkMode) {
        if (currentReadme !== nextReadme) {
            process.stderr.write('Autogenerated documentation sections are stale. Run `npm run docs:generate`.\n');
            process.exitCode = 1;
            return;
        }

        process.stdout.write('Autogenerated documentation sections are current.\n');
        return;
    }

    if (currentReadme === nextReadme) {
        process.stdout.write('README.md is already up to date.\n');
        return;
    }

    fs.writeFileSync(readmePath, nextReadme);
    process.stdout.write('Updated autogenerated documentation sections in README.md.\n');
}

main();
